/**
 * Auto-Generate data.js from folder structure
 *
 * This script automatically scans program folders and generates data.js
 * Run this whenever you add/remove/modify files in program folders
 *
 * Usage: node generate-data.js
 */

const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
    rootDir: __dirname,
    outputFile: path.join(__dirname, 'assets', 'js', 'data.js'),
    excludeDirs: ['assets', 'node_modules', '.git', '.vscode'],
    imageExtensions: ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp', '.svg'],
    exeExtension: '.exe'
};

/**
 * Check if a file is an image
 */
function isImageFile(filename) {
    const ext = path.extname(filename).toLowerCase();
    return CONFIG.imageExtensions.includes(ext);
}

/**
 * Check if a file is an executable
 */
function isExeFile(filename) {
    return path.extname(filename).toLowerCase() === CONFIG.exeExtension;
}

/**
 * Get all program folders (directories that are not excluded)
 */
function getProgramFolders() {
    const items = fs.readdirSync(CONFIG.rootDir, { withFileTypes: true });

    return items
        .filter(item => item.isDirectory())
        .filter(item => !CONFIG.excludeDirs.includes(item.name))
        .filter(item => !item.name.startsWith('.'))
        .map(item => item.name);
}

/**
 * Scan a folder and extract program information
 */
function scanProgramFolder(folderName) {
    const folderPath = path.join(CONFIG.rootDir, folderName);
    const files = fs.readdirSync(folderPath);

    // Find images
    const images = files.filter(file => isImageFile(file)).sort();

    // Find exe file
    const exeFiles = files.filter(file => isExeFile(file));
    const exeFile = exeFiles.length > 0 ? exeFiles[0] : null;

    // Extract version from exe filename (if present)
    let version = '1.0.0';
    if (exeFile) {
        const versionMatch = exeFile.match(/(\d+\.\d+\.\d+)/);
        if (versionMatch) {
            version = versionMatch[1];
        }
    }

    // Generate ID from folder name (lowercase, replace spaces with hyphens)
    const id = folderName.toLowerCase().replace(/\s+/g, '-');

    // Generate description (can be customized later in data.js)
    const description = `نظام ${folderName}`;

    return {
        id,
        name: folderName,
        folder: folderName,
        description,
        exe: exeFile || '',
        version,
        images
    };
}

/**
 * Generate the data.js file content
 */
function generateDataJS(programs) {
    const timestamp = new Date().toISOString();

    let content = `// Program data configuration
// Auto-generated by generate-data.js on ${timestamp}
//
// To update this file:
// 1. Add/remove/modify files in program folders
// 2. Run: node generate-data.js (or npm run generate)
//
// To customize descriptions:
// - Edit the description field for any program below
// - The script will preserve your custom descriptions on next run if you use the --preserve flag

const programsData = {
    programs: [
`;

    programs.forEach((program, index) => {
        const isLast = index === programs.length - 1;

        content += `        {\n`;
        content += `            id: "${program.id}",\n`;
        content += `            name: "${program.name}",\n`;
        content += `            folder: "${program.folder}",\n`;
        content += `            description: "${program.description}",\n`;
        content += `            exe: "${program.exe}",\n`;
        content += `            version: "${program.version}",\n`;
        content += `            images: [\n`;

        program.images.forEach((image, imgIndex) => {
            const isLastImage = imgIndex === program.images.length - 1;
            content += `                "${image}"${isLastImage ? '' : ','}\n`;
        });

        content += `            ]\n`;
        content += `        }${isLast ? '' : ','}\n`;
    });

    content += `    ]
};
`;

    return content;
}

/**
 * Try to preserve custom descriptions from existing data.js
 */
function preserveDescriptions(programs) {
    try {
        if (fs.existsSync(CONFIG.outputFile)) {
            const existingContent = fs.readFileSync(CONFIG.outputFile, 'utf8');

            // Extract existing descriptions using regex
            const descriptionRegex = /id:\s*"([^"]+)"[\s\S]*?description:\s*"([^"]+)"/g;
            const existingDescriptions = {};

            let match;
            while ((match = descriptionRegex.exec(existingContent)) !== null) {
                existingDescriptions[match[1]] = match[2];
            }

            // Apply existing descriptions to new programs
            programs.forEach(program => {
                if (existingDescriptions[program.id]) {
                    program.description = existingDescriptions[program.id];
                }
            });
        }
    } catch (error) {
        console.warn('⚠️  Could not preserve descriptions:', error.message);
    }
}

/**
 * Main function
 */
function main() {
    console.log('🔍 Scanning program folders...\n');

    const programFolders = getProgramFolders();

    if (programFolders.length === 0) {
        console.log('❌ No program folders found!');
        console.log('   Make sure you have folders with programs in the root directory.');
        process.exit(1);
    }

    console.log(`📁 Found ${programFolders.length} program folder(s):\n`);

    const programs = [];

    programFolders.forEach(folder => {
        const program = scanProgramFolder(folder);
        programs.push(program);

        console.log(`   ✓ ${folder}`);
        console.log(`     - Images: ${program.images.length}`);
        console.log(`     - Executable: ${program.exe || 'None found'}`);
        console.log(`     - Version: ${program.version}`);
        console.log('');
    });

    // Preserve custom descriptions if --preserve flag is used
    if (process.argv.includes('--preserve')) {
        console.log('🔄 Preserving custom descriptions...\n');
        preserveDescriptions(programs);
    }

    // Generate data.js content
    const dataJSContent = generateDataJS(programs);

    // Ensure output directory exists
    const outputDir = path.dirname(CONFIG.outputFile);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write data.js file
    fs.writeFileSync(CONFIG.outputFile, dataJSContent, 'utf8');

    console.log('✅ Successfully generated data.js!');
    console.log(`   File: ${CONFIG.outputFile}`);
    console.log(`   Programs: ${programs.length}`);
    console.log(`   Total images: ${programs.reduce((sum, p) => sum + p.images.length, 0)}`);
    console.log('\n💡 Tip: Use --preserve flag to keep custom descriptions when regenerating');
    console.log('   Example: node generate-data.js --preserve\n');
}

// Run the script
main();
